version: '3.11'

services:
  chr_pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../data/bronze/chr:/usr/data/bronze/chr
      - ../../data/silver/chr:/usr/data/silver/chr
      - ./vetstat.p12:/app/vetstat.p12
      - ./.env:/app/.env
    environment:
      - FVM_USERNAME=${FVM_USERNAME}
      - FVM_PASSWORD=${FVM_PASSWORD}
      - VETSTAT_CERTIFICATE_PASSWORD=${VETSTAT_CERTIFICATE_PASSWORD}
      - VETSTAT_CERTIFICATE_PATH=/app/vetstat.p12
    command: >
      sh -c "/opt/venv/bin/python debug_paths.py && /opt/venv/bin/python main.py --steps all --log-level INFO --progress --limit-herds-per-species 10"
    networks:
      - chr_network

networks:
  chr_network:
    driver: bridge