name: Arbejdstilsynet Inspections Pipeline

on:
  schedule:
    # Run weekly at 6 AM UTC on Mondays
    - cron: '0 6 * * 1'
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Logging level'
        type: choice
        required: true
        options:
          - WARNING
          - INFO
          - DEBUG
          - ERROR
        default: 'WARNING'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: "--max-old-space-size=4096"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        cd backend/pipelines/arbejdstilsynet_inspections
        uv pip install --system -e .

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Set up environment variables
      working-directory: backend/pipelines/arbejdstilsynet_inspections
      env:
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
      run: |
        if [ -z "$GCS_BUCKET" ]; then
          echo "Error: Required secret GCS_BUCKET is not set or is empty."
          exit 1
        fi
        echo "GCS_BUCKET=$GCS_BUCKET" > .env
        echo "Successfully created .env file with GCS_BUCKET."

    - name: Run Pipeline
      working-directory: backend/pipelines/arbejdstilsynet_inspections
      run: |
        LOG_LEVEL=${{ inputs.log_level || 'WARNING' }}
        CMD="python main.py --log-level $LOG_LEVEL"
        
        echo "Running command: $CMD"
        $CMD

    - name: Handle pipeline failure
      if: failure()
      run: |
        echo "Pipeline failed. Please check the logs above for details."
        exit 1

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pipeline-output
        path: backend/pipelines/arbejdstilsynet_inspections/data
        retention-days: 7
