name: Deploy Edge Function

on:
  push:
    branches:
      - main
    paths:
      # Trigger on changes within the backend/api directory, including the Supabase config
      - 'backend/api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Deploy Edge Function
        # Change the working directory to where the Supabase project now lives
        working-directory: backend/api
        run: |
          # Deploy the function from within the backend/api directory.
          # The CLI should automatically find the function 'api' inside './supabase/functions/api/'
          supabase functions deploy api --project-ref $PROJECT_ID --no-verify-jwt 