name: Deploy Edge Function

on:
  push:
    branches:
      - main
    paths:
      # Trigger on changes within the backend/api directory, including the Supabase config
      - 'backend/api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      
      - name: Convert YAML to JSON
        # Convert the config.yaml to config.json inside the function directory
        run: yq eval -o=json backend/api/supabase/functions/api/config.yaml > backend/api/supabase/functions/api/config.json
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Deploy Edge Function
        # Change the working directory to where the Supabase project now lives
        working-directory: backend/api
        run: |
          # Deploy the function from within the backend/api directory.
          # The CLI should automatically find the function 'api' inside './supabase/functions/api/'
          # and will now include the generated config.json
          supabase functions deploy api --project-ref $PROJECT_ID --no-verify-jwt 