name: Deploy Edge Function

on:
  push:
    branches:
      - main
    paths:
      - 'backend/api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Deploy Edge Function
        run: |
          # Create the standard Supabase functions directory structure
          mkdir -p supabase/functions/api
          
          # Copy function files to the standard location
          cp -r backend/api/* supabase/functions/api/
          
          # Deploy the function from the project root, specifying the function name
          supabase functions deploy api --project-ref $PROJECT_ID --no-verify-jwt 